spring:
  application:
    name: test4sandbox

  datasource:
    url: jdbc:h2:file:/data/employeedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true