spring:
  application:
    name: test4sandbox

  datasource:
    url: jdbc:h2:file:./src/main/resources/employeedb
    #url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
#    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
#    properties:
#      javax.persistence.schema-generation.database.action: create
    hibernate:
      entityManagerFactoryInterface: jakarta.persistence.EntityManagerFactory
      ddl-auto: create

  h2:
    console:
      enabled: true