CREATE TABLE IF NOT EXISTS employee (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    A_POSITION VARCHAR(255),
    SUPERVISOR BIGINT,
    SUBORDINATES LONGVARCHAR NOT NULL,
    CREATED_DATE DATE NOT NULL
);